version: '3'

services:
  storage.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  core.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  riversidecms.mvc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

